# Window settings
[window]
title = "Alacrittyyyyyy"
class = "Alacritty"
dimensions = { columns = 80, lines = 24 }
padding = { x = 20, y = 20 }
decorations = "None"
startup_mode = "Maximized"
opacity = 0.6
blur = true

# Font Settings
[font]
normal = { family = "Fira Code", style = "normal" }
bold = { family = "Fira Code", style = "bold" }
italic = { family = "Fira Code", style = "italic" }
size = 18.0
offset = { x = 0, y = 1 }

# Colors
[colors]
primary.background = "#000000"
transparent_background_colors = true

# Keyboard
[keyboard]
bindings = [
  { key = "V", mods = "Control", action = "Paste"  },
  { key = "F11", action = "ToggleFullscreen" },
  { key = "+", mods = "Control | Shift", action = "IncreaseFontSize" },
  { key = "-", mods = "Control", action = "DecreaseFontSize" }
]
